# Generated by Django 3.1.1 on 2020-09-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='tree_script',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
