# Generated by Django 3.1.1 on 2021-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_chat', '0006_auto_20210117_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='code',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='how_done',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='how_next',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='learn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_done',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_next',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
