# Generated by Django 3.1.1 on 2021-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_chat', '0005_auto_20201216_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_done', models.CharField(max_length=150)),
                ('how_done', models.CharField(max_length=150)),
                ('learn', models.CharField(max_length=150)),
                ('work_next', models.CharField(max_length=150)),
                ('how_next', models.CharField(max_length=150)),
                ('code', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='config',
            name='data',
            field=models.TextField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
